### ISSUE TITLE
How to make use of callback url of diawi plugin 

### ISSUE THREAD

**Issue by badrinathvm** [pacification/fastlane-plugin-diawi#15]
My idea is to slack the url of the app uploaded to Diawi , How to make use of call_back url

```
lane :uploadIPA do
   diawi(
       token: token,
       file: PATH_OF_IPA,
       password: PASSWORD_FOR_BUILD,
       callback_url: "???"
   )
end
```

```
ERROR [2020-02-18 18:42:14.33]: Error setting value 'https://i.diawi.com/testApp' for option 'callback_url'
ERROR [2020-02-18 18:42:14.33]: You passed invalid parameters to 'diawi'.
ERROR [2020-02-18 18:42:14.33]: Check out the error below and available options by running `fastlane action diawi`
WARN [2020-02-18 18:42:14.33]: Lane Context:
INFO [2020-02-18 18:42:14.33]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"uploadIPA"}
ERROR [2020-02-18 18:42:14.33]: The `callback_url` not valid.
```
Any help is appreciated.

**Comment by pacification** [comment]
Hi, @badrinathvm!
Uploaded file link is stored in `UPLOADED_FILE_LINK_TO_DIAWI`, you can use it to send message to the slack. See [Result link](https://github.com/pacification/fastlane-plugin-diawi#result-link).

**Comment by pacification** [comment]
Hi, @badrinathvm. Looks like you specified invalid URL. The `calback_url` is validated by `URI::regexp` (see [the code](https://github.com/pacification/fastlane-plugin-diawi/blob/master/lib/fastlane/plugin/diawi/actions/diawi_action.rb#L185)). So, you can manually check you callback and fix the warnings.

**Comment by badrinathvm** [comment]
@pacification can you let know the valid `callback_url`. i am seeing error 

```
diawi(
       token:"XXX",
       callback_url: "https://i.diawi.com"
   )
```

error : [08:48:34]: Error setting value 'https://i.diawi.com' for option 'callback_url'
[08:48:34]: You passed invalid parameters to 'diawi'.
[08:48:34]: Check out the error below and available options by running `fastlane action diawi`
+------------------+-----------+

**Comment by pacification** [comment]
You should pass slack callback url (i believe it's a webhook url), not any kind of diawi link.
But, there is another way to do that. You can send uploaded file link (`lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI]`) via [slack fastlane action](https://docs.fastlane.tools/actions/slack/) without using callback url.

**Comment by badrinathvm** [comment]
@pacification  this info helps and tried out. Works as expected. Thank you so much.
