### ISSUE TITLE
Timeout limit

### ISSUE THREAD

**Issue by Fl0p** [pacification/fastlane-plugin-diawi#17]
Timeout = options[:timeout].clamp(5, 240)

Very short timeout for our builds

```
00:10:02.228: Start uploading file to diawi. Please, be patient. This could take some time.
00:16:57.784: Processing file...
00:17:13.244: Processing file...
00:17:28.522: File successfully uploaded to diawi. Link: https://i.diawi.com/***

```

Need greater than 1200 sec

**Comment by Fl0p** [comment]
Can't update to 2.0 without this limit
Still on 1.4

**Comment by pacification** [comment]
Hi @Fl0p!
Timeout increased up to 1800 sec (30 min). Check 2.1.0 version.
Thanks for request.

**Comment by Fl0p** [comment]
Tnx
