### ISSUE TITLE
UI.warning doesn't exist

### ISSUE THREAD

**Issue by mradzinski** [pacification/fastlane-plugin-diawi#2]
`Unknown method 'warning', supported [:select, :message, :verbose, :error, :input, :command, :password, :header, :success, :confirm, :important, :deprecated, :command_output, :user_error!, :interactive?, :crash!, :not_implemented, :shell_error!, :build_failure!, :test_failure!, :abort_with_message!]
`

I guess you meant `UI.important`.

**Comment by pacification** [comment]
Hi, @mradzinski. Thanks for issue. Fixed in new release.
