### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by alahammad** [pacification/fastlane-plugin-diawi#5]
Hi,
There is issue when set file in fastfile, the result : 

File is not processed.
Try to upload file by yourself:

and same time the file uploaded it to diawi .

**Comment by pacification** [comment]
Hi, @alahammad. Could you share the size of your file, please?

**Comment by alahammad** [comment]
@pacification around 2 Mb.

**Comment by pacification** [comment]
Ok. I fixed that. Now, in 1.2.0 release, first status check fired in 2 sec (number provided by diawi docs). If you still have this behavior take a look at `last_hope_attempts_count` in [available options](https://github.com/pacification/fastlane-plugin-diawi#available-options).
