### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by matheuschagas** [pacification/fastlane-plugin-diawi#9]
I'm trying to upload an ipa to diawi using your plugin and the following error is shown:

`400 Bad request`

the full log you can see in https://pastebin.com/fixErGTG

**Comment by matheuschagas** [comment]
my bad, the issue is about the size of my build

**Comment by che1404** [comment]
Same problem here. The build size is not a problem in my case, it's 9MB.
Any clue?
